ESLint for JavaScript sources
ably/ably-common pull request #141
Opened 2022-03-24 16:37 UTC by QuintinWillison

I am working on new JavaScript-based tools for this repository and wanted to enhance the foundations. We're using ESLint with the Airbnb base ruleset elsewhere and it has helped spot issues and reduce bikeshedding in those locations, so I'm bringing it in here.

2022-03-25 15:21 UTC, Jmgr approved these changes
Not an expert on ESLint config but the fixes look good to me.

2022-03-28 09:35 UTC, Peter-Maguire approved these changes

2022-03-28 14:59 UTC, owenpearson requested changes

2022-03-29 09:03 UTC, QuintinWillison commented on test/agents.test.js
> +// eslint-disable-next-line import/no-dynamic-require
Oh, cool, if that'll work. 😁 I'll give that a whirl...

2022-03-29 09:28 UTC, QuintinWillison commented on test/agents.test.js
> +// eslint-disable-next-line import/no-dynamic-require
https://github.com/ably/ably-common/pull/141/commits/e3370827ae76bedee52fe569cf1a0c8782c24f54

2022-03-29 11:36 UTC, merged