Add Dart to agents.json
ably/ably-common pull request #143
Opened 2022-04-11 16:36 UTC by ikurek

I'm not sue if I got everything right, but in scope of https://github.com/ably/ably-flutter/issues/286, I wanted to add additional header with Dart runtime version to `agents`. The entire header sent by `ably-flutter` looks like this:

```
Ably-Agent: ably-java/1.2.11 dart/2.16.2 ably-flutter/1.2.13 android/31
```

So I think if should be fine with the definitions I added to `agents`, but I'm not entirely sure if configuration inside `ablyLibMappings` is correct, so additional verification would be appreciated.

2022-04-11 16:51 UTC, QuintinWillison requested changes
Just removal of that line, then this looks good to go.

2022-04-11 16:55 UTC, ikurek commented on protocol/agents.json
> +    "dart": "dart/${version}",
Removed in https://github.com/ably/ably-common/pull/143/commits/7779b8ec06af1b7fdc6aae7cffd348a68ea69f22

2022-04-11 17:14 UTC, owenpearson approved these changes
LGTM

2022-04-11 19:18 UTC, lmars approved these changes

2022-04-12 09:19 UTC, QuintinWillison approved these changes

2022-04-12 09:21 UTC, merged